FROM node:20-bullseye-slim

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

COPY . .

# Worker does not expose ports
CMD ["npm","run","worker"]

